site_name: Documentation Test Site
site_author: Alex Brown
site_url: https://sitename.example.com
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  font:
    text: Rubik
    code: Red Hat Mono
  features:
    - navigation.footer

# Page Tree
nav:
  - Home: index.md
  - Getting Started: 
    - Installation: installation.md
  - Tutorials:
    - tutorial-1.md
    - tutorial-2.md
  - Reference:
    - glossary.md
  - API: openapi_spec.md

# Extension List
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

# Extra configs
extra:
  generator: false
copyright: Copyright &copy; 2024 Alex Brown
